{{- if .Values.ingress.enabled -}}
{{- range $redundancyMode := (.Values.gateway.redundancy.enabled | ternary (list "primary" "backup") (list "")) }}
{{- $prefix := (printf "%s-%s" (include "ignition.fullname" $) $redundancyMode) -}}
{{- if empty $redundancyMode -}}
{{- $prefix = (include "ignition.fullname" $) -}}
{{- end -}}
{{- with $ -}}
{{- $host := (include "ignition.ingress.hostName" (list . $redundancyMode)) -}}
{{- $includeHost := (ne $host "*") -}}
{{- $baseAnnotations := .Values.ingress.annotations | default dict -}}
{{- $annotations := (get .Values.ingress (empty $redundancyMode | ternary "annotations" (printf "%sAnnotations" $redundancyMode))) | default dict -}}
{{- $annotations = merge $annotations $baseAnnotations -}}
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: {{ $prefix }}
  labels:
    {{- include "ignition.labels" . | nindent 4 }}
  {{- with $annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
spec:
  {{- if .Values.ingress.className }}
  ingressClassName: {{ .Values.ingress.className }}
  {{- end }}
  {{- $customTLS := (include "ignition.ingress.customTLS" (list . $redundancyMode)) -}}
  {{- if $customTLS }}
  tls:
  {{- $customTLS | nindent 2 }}
  {{- else if .Values.ingress.tls.enabled }}
  tls:
  - secretName: {{ ((print $prefix "-tls") | quote) }}
    {{- if $includeHost }}
    hosts:
    - {{ $host | quote }}
      {{- range $i := until ((include "ignition.ingress.podIndexedHostNameCount" .) | int) }}
    - {{ (include "ignition.ingress.podIndexedHostName" (list $ $i)) | quote }}
      {{- end }}
    {{- end }}
  {{- end }}
  rules:
  {{- $customRules := (include "ignition.ingress.customRules" (list . $redundancyMode)) -}}
  {{- if $customRules }}
  {{- $customRules | nindent 2 }}
  {{- else }}
  - http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: {{ $prefix }}
            port:
              {{- if .Values.gateway.tls.enabled }}
              name: https
              {{- else }}
              name: http
              {{- end }}
    {{- if $includeHost }}
    host: {{ $host | quote }}
    {{- end }}
  {{- range $i := until ((include "ignition.ingress.podIndexedHostNameCount" .) | int) }}
  {{- $podIndexedHostname := (include "ignition.ingress.podIndexedHostName" (list $ $i)) }}
  - http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: {{ $prefix }}-{{ $i }}
            port:
              {{- if $.Values.gateway.tls.enabled }}
              name: https
              {{- else }}
              name: http
              {{- end }}
    {{- if not $includeHost }}
    {{- fail "Cannot omit host with pod-indexed Ingress rules" }}
    {{- else }}
    host: {{ $podIndexedHostname | quote }}
    {{- end }}
  {{- end }}
  {{- $extraRules := (include "ignition.ingress.extraRules" (list . $redundancyMode)) -}}
  {{- if $extraRules }}
  {{- $extraRules | nindent 2 }}
  {{- end }}
  {{- end }}
---
{{- end }}
{{ end }}
{{- end }}