{{- if .Values.ingress.enabled -}}
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: {{ template "ignition.fullname" . }}
  labels:
    {{- include "ignition.labels" . | nindent 4 }}
  {{- with .Values.ingress.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
spec:
  {{- if .Values.ingress.className }}
  ingressClassName: {{ .Values.ingress.className }}
  {{- end }}
  {{- $customTLS := (include "ignition.ingress.customTLS" (list . "")) -}}
  {{- if $customTLS }}
  tls:
  {{- $customTLS | nindent 2 }}
  {{- else if .Values.ingress.tls.enabled }}
  tls:
  - secretName: {{ ((print (include "ignition.fullname" $) "-tls") | quote) }}
    hosts:
    {{- (include "ignition.ingress.hostNames" $) | nindent 4 }}
  {{- end }}
  rules:
  {{- $customRules := (include "ignition.ingress.customRules" (list . "")) -}}
  {{- if $customRules }}
  {{- $customRules | nindent 2 }}
  {{- else }}
  {{- range $redundancyMode := (.Values.gateway.redundancy.enabled | ternary (list "primary" "backup") (list "")) }}
  {{- $prefix := (printf "%s-%s" (include "ignition.fullname" $) $redundancyMode) }}
  {{- if empty $redundancyMode }}
  {{- $prefix = (include "ignition.fullname" $) }}
  {{- end }}
  {{- $host := (include "ignition.ingress.hostName" (list $ $redundancyMode)) }}
  - http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: {{ $prefix }}
            port:
              {{- if $.Values.gateway.tls.enabled }}
              name: https
              {{- else }}
              name: http
              {{- end }}
    host: {{ $host | quote }}
  {{- end }}
  {{- range $i := until ((include "ignition.ingress.podIndexedHostNameCount" .) | int) }}
  {{- $podIndexedHostname := (include "ignition.ingress.podIndexedHostName" (list $ $i)) }}
  - http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: {{ template "ignition.fullname" $ }}-{{ $i }}
            port:
              {{- if $.Values.gateway.tls.enabled }}
              name: https
              {{- else }}
              name: http
              {{- end }}
    host: {{ $podIndexedHostname | quote }}
  {{- end }}
  {{- $extraRules := (include "ignition.ingress.extraRules" (list . "")) -}}
  {{- if $extraRules }}
  {{- $extraRules | nindent 2 }}
  {{- end }}
  {{- end }}
{{- end }}
